Repository openedx/frontend-app-library-authoring, pull requests merged in 2020-10, with the labels that each got.

#16 [BD-14] Set explicit text direction in xblock-bootstrap.html
  src/library-authoring/edit-block/LibraryBlock/xblock-bootstrap.html
Labels: blended, needs triage

#17 [BD-14] Make the xblock-bootstrap.html source configurable
  .env
  .env.development
  .env.test
  src/index.jsx
  src/library-authoring/edit-block/LibraryBlock/LibraryBlock.jsx
  src/setupTest.js
  webpack.dev-stage.config.js
  webpack.dev.config.js
  webpack.prod.config.js
Labels: blended, needs triage

#11 [BD-14] Handle field-based errors for XBlock addition properly.
  src/library-authoring/common/helpers.js
  src/library-authoring/common/messages.js
  src/library-authoring/library-detail/LibraryPage.jsx
  src/library-authoring/library-detail/data/api.js
  src/library-authoring/library-detail/data/slice.js
  src/library-authoring/library-detail/data/thunks.js
  src/library-authoring/library-detail/index.scss
Labels: blended, waiting on author

#12 [BD-14] [SE-2932] Add a license field to libraries.
  src/library-authoring/common/License.jsx
  src/library-authoring/common/LicenseField.jsx
  src/library-authoring/common/data/constants.js
  src/library-authoring/common/data/shapes.js
  src/library-authoring/common/data/utils.js
  src/library-authoring/common/messages.js
  src/library-authoring/create-library/LibraryCreateForm.jsx
  src/library-authoring/edit-library/LibraryEditPage.jsx
  src/library-authoring/library-detail/LibraryPage.jsx
  src/library-authoring/list-libraries/data/api.js
Labels: awaiting prioritization, blended

#15 [BD-14] [SE-2937] Authoring page
  README.rst
  package-lock.json
  package.json
  src/index.jsx
  src/library-authoring/common/data/api.js
  src/library-authoring/common/data/constants.js
  src/library-authoring/common/data/index.js
  src/library-authoring/common/data/selectors.js
  src/library-authoring/common/data/utils.js
  src/library-authoring/common/index.scss
  src/library-authoring/common/specs/factories.js
  src/library-authoring/common/specs/helpers.jsx
  src/library-authoring/create-library/data/selectors.js
  src/library-authoring/create-library/data/slice.js
  src/library-authoring/edit-block/LibraryBlock/LibraryBlock.jsx
  src/library-authoring/edit-block/LibraryBlockPage.jsx
  src/library-authoring/edit-block/data/api.js
  src/library-authoring/edit-block/data/index.js
  src/library-authoring/edit-block/data/selectors.js
  src/library-authoring/edit-block/data/shapes.js
  src/library-authoring/edit-block/data/slice.js
  src/library-authoring/edit-block/data/thunks.js
  src/library-authoring/edit-library/data/api.js
  src/library-authoring/edit-library/data/selectors.js
  src/library-authoring/edit-library/data/slice.js
  src/library-authoring/edit-library/data/thunks.js
  src/library-authoring/library-access/data/selectors.js
  src/library-authoring/library-access/specs/LibraryAccessForm.spec.jsx
  src/library-authoring/library-access/specs/UserAccessContainer.spec.jsx
  src/library-authoring/library-detail/LibraryAuthoringPage.jsx
  src/library-authoring/library-detail/data/index.js
  src/library-authoring/library-detail/data/selectors.js
  src/library-authoring/library-detail/data/slice.js
  src/library-authoring/library-detail/data/specs/slice.spec.js
  src/library-authoring/library-detail/data/thunks.js
  src/library-authoring/library-detail/index.js
  src/library-authoring/library-detail/index.scss
  src/library-authoring/library-detail/messages.js
  src/library-authoring/library-detail/specs/LibraryAuthoringPage.spec.jsx
  src/library-authoring/list-libraries/data/selectors.js
  src/library-authoring/list-libraries/data/slice.js
  src/library-authoring/list-libraries/index.js
  src/setupTest.js
  src/store.js
Labels: architecture review, blended
