Repository openedx/frontend-app-library-authoring, pull requests merged in 2024-03, with the labels that each got.

#412 feat: add export library tags menu [FC-0049]
  src/library-authoring/studio-header-wrapper/messages.js
  src/library-authoring/studio-header-wrapper/specs/utils.spec.js
  src/library-authoring/studio-header-wrapper/utils.js
Labels: open-source-contribution, waiting for eng review

#422 chore: update readme issue list
  README.rst
Labels: open-source-contribution

#351 feat!: remove Transifex calls for OEP-58 | FC-0012
  .gitignore
  .tx/config
  Makefile
  src/i18n/index.js
  src/i18n/messages/ar.json
  src/i18n/messages/ca.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/he.json
  src/i18n/messages/id.json
  src/i18n/messages/ko_kr.json
  src/i18n/messages/pl.json
  src/i18n/messages/pt_br.json
  src/i18n/messages/ru.json
  src/i18n/messages/th.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
Labels: waiting on author, open-source-contribution
